### ISSUE TITLE
Shared Library Objects include Text Relocations

### ISSUE THREAD

**Issue by Marpin3** [Rupan/gmp#11]
Using the latest 6.1.2 version of your pre-built libraries, I noticed when compiling on Android 7 (Nougat) using "compileSdkVersion 22" the system presented the warning "Detected problems with app native libraries (please consult log for detail): libgmp.so: text relocations". If I increased the "compileSdkVersion" to 23 or above, the warning changes to a FATAL ERROR, preventing the app from running.

It seems newer versions of Android are disallowing libraries that include text relocations (TEXTRELs) within them. Doing research shows that a GCC compiler flag, -fPIC, can be used to remove text relocations when compiling. Further research showed that GMP shared libraries should use the -fPIC compiler flag by default. This prompted me to check which shared libraries included the TEXTRELs and of the 3 I was using, only the "armeabi" and "armeabi-v7a" libraries included them. Continuing my research showed -fPIC is unable to remove all text relocations from some architecture builds if the TEXTRELs are hand written in assembly; namely ARM builds.

I am logging this issue to ask if -fPIC was indeed enabled for the "armeabi" and "armeabi-v7a" builds. If so, has anyone fixed this issue in another way?

I am discussing the issue on the GMP Discussion email chain now and will most likely move to submitting it as a "bug". However, I want to make sure -fPIC was indeed used to compile the libraries before I mark it as such.

**Comment by Rupan** [comment]
Indeed it does.  Here is a snippet of a unit compilation:
```
libtool: compile:  aarch64-linux-android-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_toom63_mul -O2 -g -pedantic -fomit-frame-pointer -Wa,--noexecstack -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-strict-aliasing -fstack-protector-strong -finline-limit=300 -funswitch-loops -c toom63_mul.c  -fPIC -DPIC -o .libs/toom63_mul.o
```

**Comment by Rupan** [comment]
I've rebuilt GMP 6.1.2 for all ARM platforms using NDK r14b.  The changes are visible in pull request 12 and can be checked out in branch ```new_toolchain```.  Can you try them in your project and report whether the issue is resolved?

**Comment by Marpin3** [comment]
I pulled the libraries from "new_toolchain" and they indeed resolved my issue. Thank you for looking into this for me and resolving it so quickly.

**Comment by Rupan** [comment]
I've rebuilt all of the other shared objects, merged the changes to master, and tagged it all as bin_6.1.2_r2.
