### ISSUE TITLE
localeconv reference issue in API 19

### ISSUE THREAD

**Issue by re3el** [Rupan/gmp#6]
Hello Rupan,

Firstly a big thanks for this repo. I have used it for my work and it is working pretty fine with android API 23. But, I am facing "dlopen failed: cannot locate symbol "localeconv" referenced by libgmp.so" error while accessing the same for API 19. Kindly suggest me a fix.

Thanks

**Comment by Rupan** [comment]
Sorry for the late reply -- it seems that Gmail helpfully deprioritized email from Github.  I'll look into this soon if possible.  I recall running into some similar issue when first building this library, but forget the details.  It might be as simple as recompiling with a lower API level from the SDK.

**Comment by re3el** [comment]
Hello Michael,

Thanks for getting back. I solved the issue by building it with lower SDK
version. I forgot to update the same at github. Will do it at the earliest.

Good Day,
Yogesh

**Comment by Rupan** [comment]
Awesome.  Do you know which API level the localeconv support was added in?

**Comment by re3el** [comment]
I tried it for target-19. It worked out pretty well.

**Comment by Rupan** [comment]
I've updated the prebuilt binaries using the NDK 10e standaline toolchain at API level 19.  Would you be willing to test the updated binaries in your app and confirm that they work correctly?

**Comment by Rupan** [comment]
I confirmed (via config.log) that localconv is not detected / supported at API level 19 but is at API level 21.

**Comment by re3el** [comment]
yes! I have just made a small change in the compile script by changing the
target level to android-19. And it worked just fine :)

**Comment by Rupan** [comment]
Can you confirm that the binaries, as uploaded to the git repository (unchanged), work correctly?  I don't have a project handy at the moment to embed them in for validation.

**Comment by re3el** [comment]
yup. It works fine!

**Comment by Rupan** [comment]
Thanks for your report.
