### ISSUE TITLE
arm64-v8a architecture missing

### ISSUE THREAD

**Issue by sergeych** [Rupan/gmp#7]
can't compile for modern devices :( any ideas?

**Comment by Rupan** [comment]
Actually I hasn't realized that arm64 support had been added to the NDK.  I'll take a look at how feasible it would be.

**Comment by Rupan** [comment]
Some ABI documentation is here:

http://developer.android.com/ndk/guides/abis.html
http://brian.io/android-ndk-r10c-docs/Programmers_Guide/html/md_3__key__topics__c_p_u__support__chapter_1-section_8__a_b_is.html

And random stuff on StackOverflow:

http://stackoverflow.com/questions/29883257/ndk-r10-b-32-bit-or-64-bit-or-compile-using-both-and-how-to-achieve-it
//stackoverflow.com/questions/27287004/how-do-i-install-the-required-abi-arm64-v8a-and-build-a-titanium-app-for-the-n

**Comment by Rupan** [comment]
I've added initial code into the arm64-v8a branch, but it isn't working.  Somehow the autoconf build scripts don't like the new ABI.

**Comment by Rupan** [comment]
Ah, turns out it was a couple of minor bugs in my build scripts.  The arm64-v8a build now works and produces a shared object.

**Comment by Rupan** [comment]
I have no hardware to validate this on, and at the moment no readily-available APK to try it out in the emulator.  Sergey, please clone the repository and check out the arm64-v8a branch then validate that it works somehow.

**Comment by Rupan** [comment]
Support is available in pull request 8.

**Comment by Rupan** [comment]
I'll also add support for MIPS64 and AMD64 at some point.

**Comment by sergeych** [comment]
Big thanks!

**Comment by Rupan** [comment]
I added the x86_64 ABI build just now as well.  No time at the moment to add support for MIPS64.

You could show your appreciation by confirming that this works on real/emulated hardware, or even writing a small APK test driver ;)
